return {
  cmd = { "pyright-langserver", "--stdio" },
  root_markers = {
    ".git", -- Common Git marker
    "pyproject.toml", -- Modern Python packaging standard
    "setup.py", -- Older but common packaging script
    "setup.cfg", -- Configuration for setuptools
    "requirements.txt", -- Common location for dependencies list
    "pyrightconfig.json", -- Pyright's specific configuration file
  },
  filetypes = { "python" },
  settings = {
    python = {
      -- analysis = {
      -- typeCheckingMode = "off",
      analyzeUnannotatedFunctions = false,
      disableBytesTypePromotions = false,
      strictParameterNoneValue = false,
      enableTypeIgnoreComments = false,
      enableReachabilityAnalysis = false,
      strictListInference = false,
      strictDictionaryInference = false,
      strictSetInference = false,
      deprecateTypingAliases = false,
      enableExperimentalFeatures = false,
      reportMissingTypeStubs = false,
      reportMissingModuleSource = false,
      reportInvalidTypeForm = false,
      reportMissingImports = false,
      reportUndefinedVariable = false,
      reportAssertAlwaysTrue = false,
      reportInvalidStringEscapeSequence = false,
      reportInvalidTypeVarUse = false,
      reportSelfClsParameterName = false,
      reportUnsupportedDunderAll = false,
      reportUnusedExpression = false,
      reportWildcardImportFromLibrary = false,
      reportAbstractUsage = false,
      reportArgumentType = false,
      reportAssertTypeFailure = false,
      reportAssignmentType = false,
      reportAttributeAccessIssue = false,
      reportCallIssue = false,
      reportGeneralTypeIssues = false,
      reportInconsistentOverload = false,
      reportIndexIssue = false,
      reportInvalidTypeArguments = false,
      reportNoOverloadImplementation = false,
      reportOperatorIssue = false,
      reportOptionalSubscript = false,
      reportOptionalMemberAccess = false,
      reportOptionalCall = false,
      reportOptionalIterable = false,
      reportOptionalContextManager = false,
      reportOptionalOperand = false,
      reportRedeclaration = false,
      reportReturnType = false,
      reportTypedDictNotRequiredAccess = false,
      reportPrivateImportUsage = false,
      reportUnboundVariable = false,
      reportUnhashable = false,
      reportUnusedCoroutine = false,
      reportUnusedExcept = false,
      reportFunctionMemberAccess = false,
      reportIncompatibleMethodOverride = false,
      reportIncompatibleVariableOverride = false,
      reportOverlappingOverload = false,
      reportPossiblyUnboundVariable = false,
      reportConstantRedefinition = false,
      reportDeprecated = false,
      reportDuplicateImport = false,
      reportIncompleteStub = false,
      reportInconsistentConstructor = false,
      reportInvalidStubStatement = false,
      reportMatchNotExhaustive = false,
      reportMissingParameterType = false,
      reportMissingTypeArgument = false,
      reportPrivateUsage = false,
      reportTypeCommentUsage = false,
      reportUnknownArgumentType = false,
      reportUnknownLambdaType = false,
      reportUnknownMemberType = false,
      reportUnknownParameterType = false,
      reportUnknownVariableType = false,
      reportUnnecessaryCast = false,
      reportUnnecessaryComparison = false,
      reportUnnecessaryContains = false,
      reportUnnecessaryIsInstance = false,
      reportUnusedClass = false,
      reportUnusedImport = false,
      reportUnusedFunction = false,
      reportUnusedVariable = false,
      reportUntypedBaseClass = false,
      reportUntypedClassDecorator = false,
      reportUntypedFunctionDecorator = false,
      reportUntypedNamedTuple = false,
      reportCallInDefaultInitializer = false,
      reportImplicitOverride = false,
      reportImplicitStringConcatenation = false,
      reportImportCycles = false,
      reportMissingSuperCall = false,
      reportPropertyTypeMismatch = false,
      reportShadowedImports = false,
      reportUninitializedInstanceVariable = false,
      reportUnnecessaryTypeIgnoreComment = false,
      reportUnusedCallResult = false,
      -- },
    },
  },
}
