return {
  -- {
  --   -- "neovim/nvim-lspconfig",
  --   "williamboman/mason.nvim",
  --   dependencies = {
  --     "WhoIsSethDaniel/mason-tool-installer.nvim",
  --     -- { "j-hui/fidget.nvim", opts = {}, }
  --   },
  --   event = { "BufReadPre", "BufNewFile" },
  --   config = function()
  --     local mason = require("mason")
  --     mason.setup({
  --       ui = {
  --         border = "single",
  --       },
  --     })
  --
  --     -- local ensure_installed = vim.tbl_keys(servers or {})
  --     local ensure_installed = {}
  --     vim.list_extend(ensure_installed, {
  --       "bashls",
  --       "clangd",
  --       "cssls",
  --       "dockerls",
  --       "docker_compose_language_service",
  --       "emmet_ls",
  --       "gopls",
  --       "html",
  --       "hyprls",
  --       "jsonls",
  --       "lua_ls",
  --       "marksman",
  --       "neocmake",
  --       "pyright",
  --       "nil_ls",
  --       "rust_analyzer",
  --       "terraformls",
  --       "texlab",
  --       "ts_ls",
  --       "volar",
  --       "yamlls",
  --       --
  --       "black",        -- Python code formatter
  --       "clang-format", -- C++ code formatter
  --       "codespell",    -- Spell checker for code
  --       "debugpy",      -- Python debugger
  --       "eslint",       -- JavaScript code linter
  --       "yamllint",     -- YAML code linter
  --       "markdownlint", -- Markdown linter
  --       "isort",        -- Python code formatter
  --       "pylint",       -- Python code linter
  --       "nixpkgs-fmt",  -- Nix code formatter
  --       "stylua",       -- Lua code formatter
  --       "tex-fmt",      -- LaTeX code formatter
  --     })
  --
  --     require("mason-tool-installer").setup({ ensure_installed = ensure_installed })
  --   end,
  -- },
}
